(function(){
'use strict';
var S=window.BANews, main=document.getElementById('newsInner'), list=document.getElementById('news-list');
function node(tag,cls,text){var e=document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e;}
function pair(target,n){if(window.baPair){var en=node('span','',n.title);en.lang='en';var ko=node('span','',n.ko||n.title);ko.lang='ko';target.appendChild(en);target.appendChild(ko);}else target.textContent=n.title;}
function picture(n){var img=node('img');img.src=S.imageURL(n.image);img.alt=n.imageAlt||n.title;img.loading='lazy';img.onerror=function(){img.hidden=true;img.style.display="none";};return img;}
function link(n,cls){var href=S.link(n),e=node(href?'a':'div',cls);if(href)e.href=href;e.style.color='inherit';e.style.textDecoration='none';return e;}
function renderMain(items){main.textContent='';if(!items.length){main.appendChild(node('p','','No news available.'));return;}
var f=items[0],featured=node('div','news-featured'),body=link(f,'news-featured-body');body.appendChild(node('span','news-feat-date',f.date.replace(/-/g,'.')));var title=node('p','news-title-featured');pair(title,f);body.appendChild(title);if(S.link(f))body.appendChild(node('span','arrow-link',window.BA_LANG==='ko'?'읽기 ↘︎':'Read ↘︎'));featured.appendChild(body);var visual=link(f,'news-featured-img');visual.appendChild(node('div','ni-grid'));if(f.image)visual.appendChild(picture(f));var ph=node('div','ni-ph');ph.appendChild(node('span','ni-icon','📡'));ph.appendChild(node('span','ni-label','FEATURED IMAGE'));visual.appendChild(ph);featured.appendChild(visual);main.appendChild(featured);
var sub=node('div','news-sub-list'),block=node('div','news-sub-block');items.slice(1,3).forEach(function(n){var item=link(n,'news-sub-item');item.appendChild(node('span','news-sub-date',n.date.replace(/-/g,'.')));var row=node('div','news-sub-row'),t=node('p','news-title-sub');pair(t,n);row.appendChild(t);if(S.link(n))row.appendChild(node('span','arrow-link',window.BA_LANG==='ko'?'읽기 ↘︎':'Read ↘︎'));item.appendChild(row);block.appendChild(item);});sub.appendChild(block);sub.appendChild(node('div','news-sub-divider'));var more=node('div','news-show-more'),a=node('a','arrow-link',window.BA_LANG==='ko'?'더 보기 ↘︎':'Show More ↘︎');a.href=S.url('html/news.html');more.appendChild(a);sub.appendChild(more);main.appendChild(sub);
}
function renderList(items){list.textContent='';document.getElementById('pagination').textContent=items.length+' ARTICLES';if(!items.length){list.appendChild(node('p','','No news available.'));return;}items.forEach(function(n,i){var item=link(n,'news-item fade-in visible '+(i===0?'featured':'row'));var visual=node('div',i===0?'ni-image':'ni-thumb');if(n.image)visual.appendChild(picture(n));item.appendChild(visual);var left=node('div','ni-left');left.appendChild(node('span','ni-tag',n.tag));left.appendChild(node('div','news-title',n.title));left.appendChild(node('span','news-date',n.date.replace(/-/g,' / ')));item.appendChild(left);list.appendChild(item);});filter();}
function filter(){var search=document.getElementById('search-input');if(!search)return;var q=search.value.toLowerCase(),found=0;list.querySelectorAll('.news-item').forEach(function(item){var visible=item.querySelector('.news-title').textContent.toLowerCase().indexOf(q)!==-1;item.hidden=!visible;item.style.display=visible?'':'none';if(visible)found++;});var empty=document.getElementById('news-empty-search');if(!empty){empty=node('p','','No matching news.');empty.id='news-empty-search';list.appendChild(empty);}empty.hidden=found>0||!q;}
function load(){return S.list().then(function(items){if(main)renderMain(items.slice(0,3));if(list)renderList(items);}).catch(function(e){(main||list).textContent='News could not be loaded. '+e.message;});}
if(main||list){load();if(list)document.getElementById('search-input').addEventListener('input',filter);window.addEventListener('storage',load);window.addEventListener('pageshow',load);}
}());
